---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dds-shape-demo-sub-1
spec:
  selector:
    matchLabels:
      app: dds-shape-demo-sub-1
  replicas: 1 # 1
  template:
    metadata:
      labels:
        app: dds-shape-demo-sub-1
    spec:
      containers:
      - name: dds-shape-demo-sub-1
        image: dds-shape-demo-sub-1:1.0.0
        env:
        - name: DDS_LOG_LEVEL
          value: "1"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10    
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
          resources:
          limits:
          # memory: 128Mi
          securityContext:
          # privileged: false

---
kind: Service
apiVersion: v1
metadata:
  name: dds-shape-demo-sub-1
spec:
  ports:
    - protocol: TCP
      port: 8080    
      targetPort: 8080
  selector:
    app: dds-shape-demo-sub-1
